FROM node:24 AS angular-build
WORKDIR /app
COPY ./ReleaseNotes.UI ./ReleaseNotes.UI
WORKDIR /app/ReleaseNotes.UI
RUN npm ci
RUN npm audit
RUN npm run build --omit=dev

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS dotnet-build
WORKDIR /src
COPY ./ReleaseNotes.API .
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=angular-build /app/ReleaseNotes.UI/dist /app/wwwroot
COPY --from=dotnet-build /app/publish .

EXPOSE 8080
EXPOSE 8443
ENTRYPOINT ["dotnet", "ReleaseNotes.API.dll"]
