apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany # Todo check this out
  resources:
    requests:
      storage: 2Gi