apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: {{ .Values.namespace }}
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany # Todo check this out
  hostPath:
    path: /data/postgresql